### ISSUE TITLE
[Pipe Dream] Merge code with Ohana3DS developer

### ISSUE THREAD

**Issue by TheGag96** [Sammi-Husky/Sm4sh-Tools#23]
When I think about the Sm4sh modding community and how it would best flourish I think about what it would be like to have a centralized editor for the game's files, like BrawlBox was for Brawl. And even strictly speaking from a moveset editing perspective, it's a bit difficult/awkward to make changes to a character's moves without being able to immediately see where the hitboxes start/end in the animations and where they are in relation to the model. This is why BB v0.68b is so much more useful at times than just PSA alone.

What's great though is that, at least for the 3DS, we have a way to display models/animations with Ohana3DS Rebirth. And, luckily enough, it's being developed in C#, just like your Sm4sh tools. I highly suggest you contact gdkchan and talk to him about joining forces and making a more unified editor together. Great stuff could happen.

**Comment by Sammi-Husky** [comment]
In the long term, i planned on having SM4SHCommand's functionality split into an IDE and a library for compiling moveset scripts from plaintext. At around that point, i also came up with the idea to have the ability to convert to and from proprietary formats and use known libraries to develop and display the models and moveset script together rather than working directly with the formats that the games use. It's much easier to manipulate and work with displaying animations and models if they're in a known format like .dae for example. 

The way i intend for this to work is to have the compiler platform also handle building params, msc, and models + animations from the workspace and compile them into the folder structure for the specific platform the files will be used for (WiiU vs 3ds.) so that one simply has to drag and drop the files and be off the the races. For developing movesets, simply clicking a button like "Play" or "Preview" much like Visual Studio's debugging features would open a new window (or docked tab) that would play everything. With this comes some difficulty though in that some game context simply can't be inferred (variables and such being set for certain hitboxes to show).

This is all fairly far off into the future, but i figured i would at least share some of my thoughts on the matter :)
