### ISSUE TITLE
Sequence contains no matching element identifier/fix suggestion

### ISSUE THREAD

**Issue by ghost** [Sammi-Husky/Sm4sh-Tools#68]
Might I suggest adding in a move identifier (Human name/Hex) or allowing multiple spellings and ignoring case on commands?

Identifier ex: Sequence (AttackAirN, 0x12345678, etc.) contains no matching element (Invalid command here)

Ex: Allow_Interupt -> Allow_Interrupt, Allow_Interupt, AlLoW_INterUPT, etc.

**Comment by Sammi-Husky** [comment]
Both FITX and SM4SHCommand will allow overriding the event dictionary with a compatible events.cfg. I understand the frustration and issues with needing perfect spelling and casing but i think requiring those are necessary parts of creating languages. It'd be incredibly confusing for learning coders or even experienced ones to see all these different (valid) spellings/mnemonics for commands. 

It's necessary that the community settles on a standardized library so that info in blog posts, tutorials, and videos will be the same across all setups and time periods.

I do know however that having so many parameters and functions and expecting people to fluently code with them is an increasingly tall order. It's here where distributing auto-complete files for applications like notepad++ and Atom is imperative, in addition to providing autocomplete out of the box with SM4SHCommand.

In the future SM4SHCommand will be updated to use FITX as a backend and become more of an IDE similar to Visual Studio for example. For most users this will become the default moveset editing tool, and autocomplete will be present there. Until then, there are some autocomplete files provided by members of the community for Atom and the like. I'll probably update the repo readme for SMRSHCommand with links to them and/or include them in the download.

Apologies for the extremely long post, but rest assured i hear your feedback. I'll be addressing it to some degree by standardizing the naming scheme for commands (either all lowecase or uppercase for example) to help alleviate issues until SM4SHCommand is reworked. Until then, you can edit or create your own eventd.cfg file and use it to override the internal event dictionaries to your liking, though im aware its not a perfect solution as it is tedious. 

I'll be closing this issue for now since i wont be implementing this particular suggestion, but thank you for the feedback.
